Given a 2D list, create a numpy 2D array using it.
Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Print the Numpy array.

In [1]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
Print the elements of array.

In [2]:
import numpy as np
a=np.zeros(10,dtype=int)
a[4]=1
for i in a:
    print(i,end=' ')

0 0 0 0 1 0 0 0 0 0 

======================================================================================================================

In [4]:
#guessing the output
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [18]:
#randint() takes a range as argument and returns a random integer lying in that range
np.random.randint(4,10)

5

In [21]:
#Syntax for creating a random integer array ranging from 0 to 10 of size (4, 4)
np.random.randint(10, size = (4, 4))  #size is taken as an argument and the first argument refers to the upper limit of the range

array([[5, 7, 5, 5],
       [4, 1, 1, 1],
       [7, 6, 7, 0],
       [2, 6, 1, 4]])

In [28]:
#Syntax for creating a random integer array ranging from 0 to 4 of size 4
np.random.randint(4,size=4)

array([2, 1, 3, 1])

======================================================================================================================

Create an array with values ranging consecutively from 9 to 49 (both inclusive).
Print the Numpy array.

In [30]:
a=np.arange(9,50)
for i in a:
    print(i,end=' ')

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

Create an integer identity matrix of size (5, 6).
Print the Numpy array.

In [32]:
b=np.eye(5,6,dtype=int)
print(b)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.

In [40]:
import numpy as np
b=np.linspace(0,5,10)[1:9] #first and last(i.e. 0 and 5) are to be excluded
for i in b:   #start=0; end=5; num of point=10
    print(round(i,2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements.

In [44]:
import numpy as np
a=np.array([1,2,0,0,4,0])
ind=np.where(a!=0)   #where() returns a tuple in which indices of the condition are present
for i in ind[0]:
    print(i,end=' ')

0 1 4 

Given an integer array of size 10. Print the index of elements which are multiple of 3.
Note: Generate the following array
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [50]:
import numpy as np
a=np.arange(1,20,2)
ind=np.where(a%3==0)
ind
for i in ind[0]:
    print(i,end=' ')
 

1 4 7 

Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [55]:
import numpy as np
a=np.arange(1,11)
odd=np.where(a%2!=0)
a[odd]=-1
for i in a:
    print(i,end=' ')

-1 2 -1 4 -1 6 -1 8 -1 10 

Given an integer array of size 9 and replace the first occurrence of maximum value by 0?
Note: Generate the following array
array([11, 2, 13, 4, 15, 6, 27, 8, 19])

In [63]:
import numpy as np
a=np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
maxv=a.max()
ind=np.where(a==maxv)
a[ind]=0
for i in a:
    print(i)

11
2
13
4
15
6
0
8
19


Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [72]:
import numpy as np
a=np.arange(1,11)
a[2:8]*=-1
for i in a:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
Print the Numpy array.

In [78]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
ind=np.where(height>155)
for i in ind[0]:
    print(age[i]," ",height[i])


15   156
19   180
20   162
21   157
22   158
23   179
16   182
18   183
20   159
15   160
17   172


Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:
 [[21 20 19 18 17]
  [16 15 14 13 12]
  [11 10  9  8  7]
  [ 6  5  4  3  2]]
Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1.

In [87]:
import numpy as np
a=np.array([[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]] )
new_a=a[a[:,1].argsort()]  
print(new_a)        
#a[:,1] returns the whole 1st column.a[:,1].argsort() returns the sorted index position of that column.And a[a[:,1].argsort()] gives the sorted array by column

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [88]:
a[:,1].argsort() #argsort()

array([3, 2, 1, 0], dtype=int64)

### year2017.csv using numpy

Find value of killed column only where country == ‘United States’?
Print 0 in place of missing values.
Print count of Killed as integer value.

In [102]:
import csv
import numpy as np
with open('Datasets/year2017.csv',encoding='utf-8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    killed=[]
    country=[]
    for row in file_data:
        killed.append(row['Killed'])
        country.append(row['Country'])
        
    np_killed = np.array(killed)
    np_country = np.array(country)
    
    np_killed[np_killed=='']='0.0'
    bool_arr = np_country=='United States'
    
    a = np.array(np_killed[bool_arr],dtype=float)
    a = np.array(a,dtype=int)

    for i in a:
        print(i)        
    

0
5
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
1
0
0
1
3
0
0
0
0
0
2
0
1
2
0
0
0
0
0
1
0
0
2
0
0
0
0
0
0
1
0
0
1
1
1
59
0
0
0
0
8
0
0
0
3
0
0
1


Find total number of people killed from USA?
Note: Some columns of killed are empty so replace them by 0.
Print count of Killed as integer value.

In [103]:
import csv
import numpy as np
with open('Datasets/year2017.csv',encoding='utf-8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    killed=[]
    country=[]
    for row in file_data:
        killed.append(row['Killed'])
        country.append(row['Country'])
        
    np_killed = np.array(killed)
    np_country = np.array(country)
    
    np_killed[np_killed=='']='0.0'
    bool_arr = np_country=='United States'
    
    a = np.array(np_killed[bool_arr],dtype=float)
    a = np.array(a,dtype=int)
    print(sum(a))
    

95


### terrorismData.csv using numpy

Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)
Print count of NumberOFAttack as integer value.

In [106]:
#approach is to find the indices of the elements between 10 and 20 and then creating an array of those indices and printing its sizew

import csv
import numpy as np
with open('Datasets/terrorismData.csv',encoding='utf-8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    day=[]
    for row in file_data:
        day.append(row['Day'])
    np_day=np.array(day,dtype=float)
    np_day=np.array(np_day,dtype=int)
    ind=np.where((np_day>=10) & (np_day<=20))
    ind=np.array(ind)
    print(ind.size)
    

66330


Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).
Note Ignore the case where day is 0
Print count of NumberOFAttack as integer value.

In [110]:
import csv
import numpy as np
with open('Datasets/terrorismData.csv',encoding='utf-8') as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    date = []
    for row in file_data:
        date.append([row['Day'],row['Month'],row['Year']])
    
    np_date = np.array(date,dtype = int)
    np_date = np_date[(np_date[:,2]==2010) & (np_date[:,1]==1) & (np_date[:,0]>=1)]
    print(np_date.shape[0])


271


As we knew the Kargil ( in Jammu and Kashmir) War that took place between May 1999 and July 1999 (3 Months) ,so there was a huge conflict in Kashmir Valley during this period.
In this dataset, there is no information regarding the war between the two countries to find out the casualty during the war.
So find out the attack in this period in which maximum casualties happened.
Print the count of casualties (as integer), city in which that attack happened and name of attack group.
Note : Casualty = Killed + Wounded.Fill the empty value in killed or wounded feature to 0.

In [111]:
import numpy as np
import csv
with open('Datasets/terrorismData.csv',encoding = 'UTF-8') as file_obj:
    file_data = csv.DictReader(file_obj,skipinitialspace=True)  
    casualty = []
    city = []
    for row in file_data:
        if(row['State'] == 'Jammu and Kashmir' and row['Year'] == '1999'):
            if(row['Month']=='5' or row['Month']=='6' or row['Month']=='7'):
                city.append([row['City'],row['Group']])
                casualty.append([row['Killed'],row['Wounded']])
    casualty = np.array(casualty)
    city = np.array(city)
    casualty[casualty == ''] = '0.0'
    casualty = np.array(casualty,dtype = float)
    casualty = np.array(casualty,dtype = int)
    casualty = casualty[:,0] + casualty[:,1]
    index = np.argmax(casualty)  #returns the index of max valued element
    print(casualty[index],city[index][0],city[index][1])
        


22 Kargil District Separatists


Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.
Note: Casualty=Killed +Wounded
Print count of Casualty as integer value.

In [114]:
import numpy as np
import csv
with open('Datasets/terrorismData.csv',encoding = 'UTF-8') as file_obj:
    file_data = csv.DictReader(file_obj,skipinitialspace=True)  
    casualty = []
    for row in file_data:
        if(row['State'] == 'Jharkhand' or row['State'] == 'Odisha' or row['State'] == 'Andhra Pradesh' or row['State'] == 'Chhattisgarh'):
            casualty.append([row['Killed'],row['Wounded']])
    casualty = np.array(casualty)
    city = np.array(city)
    casualty[casualty == ''] = '0.0'
    casualty = np.array(casualty,dtype = float)
    casualty = np.array(casualty,dtype = int)
    casualty = casualty[:,0] + casualty[:,1]
    print(sum(casualty))       

5628


Find top 5 Indian Cities which has most number of casualties ?
Print top 5 cities along with total casualties in that city. Print count of Casualty as integer value.
Note: Ignoring the City which is Unknown.
Casualty = Killed + Wounded.

In [121]:
import csv
import numpy as np
casualty=[]
city=[]
#filter out the data here
with open('Datasets/terrorismData.csv',encoding='ISO-8859-1') as data:
    reader= csv.DictReader(data)
    for row in reader:
        if row['Country'] =='India':
            city.append(row['City'])    
            casualty.append([row['Killed'],row['Wounded']]) 
npcasualty=np.array(casualty)
npcity=np.array(city)
#convert empty values in killed and wounded feature to 0
npcasualty[npcasualty ==''] = 0
#convert string to float
npcasualty=np.array(npcasualty, dtype=float)
# sum up the killed and wounded feature to find out casualty
npcasuality=np.sum(npcasualty,axis=1)
def cityCasualty(cityarr,casualtyarr):
    arr=[]
    unique=np.unique(cityarr)
    for i in unique:
        index,=np.where(cityarr==i)
        sumCasualty=casualtyarr[index].sum()
        arr.append([sumCasualty,i])
    arr.sort(reverse=True)
    return arr
arr=cityCasualty(npcity,npcasualty)
for i in range(6):
    if arr[i][1]!='Unknown':
        print(arr[i][1],int(arr[i][0]))

Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


Find the most frequent day of attack in a terrorismDataset ?
Note: Here np.unique can be used.
Print count of frequent day and number of attack as Integer value.

In [123]:
import numpy as np
import csv

with open('Datasets/terrorismData.csv',encoding = 'UTF-8') as file_obj:
    file_data = csv.DictReader(file_obj,skipinitialspace=True)
    
    day = []
    
    for row in file_data:
        day.append(row['Day'])
    
    day = np.array(day)
    unique,counts = np.unique(day,return_counts = True)  #returns the count of each unique value
    index = counts.argmax()
    print(unique[index],counts[index])

15 6500
